name: Deploy Aura Portal to IPFS
on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Pin to IPFS
        id: deploy
        uses: anantaramdas/ipfs-pinata-deploy-action@v1.6.4
        with:
          pin-name: 'Aura Portal'
          path: './'
          pinata-api-key: ${{ secrets.PINATA_API_KEY }}
          pinata-secret-api-key: ${{ secrets.PINATA_SECRET_API_KEY }}

      - name: Get IPFS Hash
        run: echo "Aura is live at CID ${{ steps.deploy.outputs.hash }}"
